### ISSUE TITLE
App Is Always Active

### ISSUE THREAD

**Issue by user44000** [Tetr4/CompassTile#3]
The app is always running in the background even when the tile isn't turned on. 
![Screenshot_20240720-133910_F-Droid](https://github.com/user-attachments/assets/eb7e39c4-b1a5-47ca-83fd-bb54bdf12e79)
![Screenshot_20240720-134311_FOSS Browser](https://github.com/user-attachments/assets/cdad4d4a-fb56-4a2b-b796-12d3a9e1f8a6)

**Comment by Tetr4** [comment]
Hi, thank you for the report (and for using my app) 🙏

Sadly this is not something I can fix. There is a [bug in Android 14](https://issuetracker.google.com/issues/299506164) that causes a crash when clicking on the tile and the workaround for that problem (see code [here](https://github.com/Tetr4/CompassTile/blob/master/app/src/main/java/de/klimek/compass/TileService.kt#L24-L25)) will always show the app as an "active app" even if the tile is not enabled.

Luckily there is **no impact on battery or performance**:
- It will only listen to sensor data while the tile is actually enabled and on screen.
- The system will still kill the app after some time in the background, just as if it were not an "active app".

Let's hope that this will be fixed with Android 15 😬

**Comment by Tetr4** [comment]
Fixed in Android 15 🥳
